# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MilvusBackup < Formula
  desc ""
  homepage "https://github.com/zilliztech/milvus-backup"
  version "0.4.19"

  on_macos do
    on_intel do
      url "https://github.com/zilliztech/milvus-backup/releases/download/v0.4.19/milvus-backup_Darwin_x86_64.tar.gz"
      sha256 "ebc49ef84f318593c796e2000927c56681748abaf993edf368377af5ae777abd"

      def install
        bin.install "milvus-backup"
      end
    end
    on_arm do
      url "https://github.com/zilliztech/milvus-backup/releases/download/v0.4.19/milvus-backup_Darwin_arm64.tar.gz"
      sha256 "33f870f4076856d1a5452f72976e4038392202346b00e50fbffc25054aa5a6a7"

      def install
        bin.install "milvus-backup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zilliztech/milvus-backup/releases/download/v0.4.19/milvus-backup_Linux_x86_64.tar.gz"
        sha256 "292b4a7e267fcd41f41279e053d47efd8e5a213f2a3a99d3323494da10a97c3d"

        def install
          bin.install "milvus-backup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zilliztech/milvus-backup/releases/download/v0.4.19/milvus-backup_Linux_arm64.tar.gz"
        sha256 "8a70f8e1a921c2ac05f4b8d5a2ef0fe5f8bbb3bb5e9afad0bdef7cea989c0393"

        def install
          bin.install "milvus-backup"
        end
      end
    end
  end
end
