# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MilvusBackup < Formula
  desc ""
  homepage "https://github.com/zilliztech/milvus-backup"
  version "0.4.20"

  on_macos do
    on_intel do
      url "https://github.com/zilliztech/milvus-backup/releases/download/v0.4.20/milvus-backup_Darwin_x86_64.tar.gz"
      sha256 "6e16ab12aabe3ea0ed899f3d458f6537de131a12e58cbb48349b5abc5f77601a"

      def install
        bin.install "milvus-backup"
      end
    end
    on_arm do
      url "https://github.com/zilliztech/milvus-backup/releases/download/v0.4.20/milvus-backup_Darwin_arm64.tar.gz"
      sha256 "535f10c17538207ad99c532dad6cd5e01dc187722ccc362a517a837fd9b07340"

      def install
        bin.install "milvus-backup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zilliztech/milvus-backup/releases/download/v0.4.20/milvus-backup_Linux_x86_64.tar.gz"
        sha256 "4c5834140e72ee6124222b77c3bc37a5a9243090818f0886f5fa6eaf1bcaf9a7"

        def install
          bin.install "milvus-backup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zilliztech/milvus-backup/releases/download/v0.4.20/milvus-backup_Linux_arm64.tar.gz"
        sha256 "dad87ba41437837475b67444677a4bbb130387976b2c96ed4c66d58de6a73a10"

        def install
          bin.install "milvus-backup"
        end
      end
    end
  end
end
